app = "banani-lead-management"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/api/ping"
  protocol = "http"
  
[http_service.concurrency]
  type = "requests"
  hard_limit = 1000
  soft_limit = 100

# Increase request timeout and body size limits for file uploads
[http_service.http_options]
  response_timeout = "60s"
  idle_timeout = "60s"
  h2_backend = true

[env]
  PORT = "3000"
  NODE_ENV = "production"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
